/* Generado por tools/gen_protos.py -- NO editar a mano. */
#ifndef PORT_IDE_PROTOS_H
#define PORT_IDE_PROTOS_H

#include "fpgfile.hpp"

/* ---- divpaint.cpp ---- */
void quitar_textura(void);
byte get_color(int x,int y);
void test_mouse_box(int a,int b,int c, int d);
void test_mouse_box2(int a,int b,int c, int d);
void test_mouse(void);
void edit_scr(void);
void edit_mode_0(void);
void edit_mode_1(void);
void edit_mode_2(void);
void edit_mode_3(void);
void edit_mode_4(void);
void edit_mode_5(void);
void select_caja(int n);
void edit_mode_6(void);
void select_circulo(int n);
void edit_mode_7(void);
void select_spray(int n);
void edit_mode_8(void);
void edit_mode_9(void);
void barra_bloque(int n);
void edit_mode_10(void);
void test_anterior(void);
void test_siguiente(void);
void test_sel(void);
void test_mab(void);
void corta_mapa(void);
void box2mab(void);
void mab_delete(void);
void mab_regla(void);
void mab_invertir(void);
void mab_mascara(void);
void mab_aclarar(byte color_aclarar);
void mab_antialias(void);
int edit_mode_6_box(int s);
int edit_mode_6_box_auto(int s);
void mab_line(int x0, int y0, int x1, int y1);
void find_first_x_from(int xi,int y);
void rellenar_poligono(void);
int edit_mode_6_lines(int s);
int edit_mode_6_fill(int s);
int edit_mode_6_boxes(int s);
void edit_mode_11(void);
void edit_mode_12(void);
void write_char(int x, int y, byte c);
void write_char2(int x, int y, byte * si, int font_an, int font_al);
void edit_mode_13(void);
void bezier(int x0,int y0,int x1,int y1,int _x0,int _y0,int _x1,int _y1,int inc0);
void line0(int x0, int y0, int x1, int y1, int inc0);
void line(int x0, int y0, int x1, int y1, int inc0);
void pixel(byte *p);
void pixel_sin_mask(byte *p);
void line_pixel(int x,int y);
void _line_pixel(int x,int y);
void caja(int x0,int y0,int x1,int y1);
void circulo(int x0,int y0,int x1,int y1,int relleno);
void circulo_scan(int x,int y,int an);
void circulo_scan2(int x,int y,int an);
void regla_edicion(void);
void mover(byte * sp, int an, int al);
void efectos(void);
void cuentagotas(void);
int editable(int *n);
int editable_seleccion(int *n,int x,int y);
void dibuja_regla(void);
void dibuja_regla_seleccion(byte * p, int c, int d, int x, int y);
void ayuda_dibujo(int n);
void zoom_map2(void);
void volcado_edicion(void);
void select_mode(void);
void select_fx(int n,int * efecto);
void select_fill(int n);
void select_box(int n);
int select_icon(int icono_x,int * iconos);
void volcado_raton(void);
void volcado_raton_a(void);
void volcado_raton_b(void);
void select_mascara(int n);
void pinta_ventana_mascara(byte * p,int c,int d);
void FreePaintThumbs(void);
int crear_mapbr_thumbs(struct t_listboxbr * l);
void select_color(int n);
void cambia_mapa(int adelante);
void color_up(void);
void color_down(void);
void pinta_ventana_colores(byte * p,int c,int d);
void pinta_ventana_colores2(byte * p,int c,int d,int col);
void ajusta_caja(int*a,int*b,int*c,int*d);
void mover_barra(void);
void select_zoom(void);
void mover_zoom(void);
void dibuja_barra(int _an);
void coord_barra(void);
void anal_barra(int an, int al);
int nueva_barra(int an, int al);
void volcar_barras(int oscurecidas);
void vuelca_barra(byte * p, int real_an, int x, int y, int an, int al);
void vuelca_barra_oscurecida(byte * p, int real_an, int x, int y, int an, int al);
void put_barra(int x,int y,int n);
void put_barra_inv(int x,int y,int n);

/* ---- divpalet.cpp ---- */
void find_colors(void);
void init_ghost(void);
byte fast_find_color(byte fr,byte fg,byte fb);
void crear_ghost(int puntos);
void crear_ghost_vc(int m);
void crear_ghost_slow(void);
void create_dac4(void);
byte find_color(byte r,byte g,byte b);
byte find_color_not0(byte r,byte g,byte b);
void ord_paleta0(void);
void ord_paleta1(void);
void ord_paleta2(void);
void ord_paleta3(void);
byte find_ord(byte * dac);
byte media(byte a,byte b);
void make_near_regla(void);
void calcula_regla(int n);
int hay_mapas(void);
void LoadPal(void);
void Guarda_Pal(void);
void SaveAsPal(void);
void RefPalAndDlg(int no_tocar_mapas,int guardar_original);
void ordena1(void);
void ordena2(void);
void ordena0(void);
void ordena_paleta(void);
word find_ord2(byte * dac);
void fusiona_paleta(void);
void fusionar_paletas(void);
word new_find_ord(byte * dac);
void crear_paleta(void);
void preparar_tapiz(void);
void rescalar(byte *si,int sian,int sial,byte *di,int dian,int dial);
void InterPal1(void);
void InterPal2(void);
void InterPal0(void);
void EditPal(void);

/* ---- divmouse.cpp ---- */
int mouse_in(int x, int y, int x2, int y2);
int wmouse_in(int x, int y, int an, int al);
void set_mouse(word x, word y);
void read_mouse(void);
void libera_drag(void);
void read_mouse2(void);

/* ---- divbrow.cpp ---- */
void imprime_rutabr(void);
void crear_thumbs(void);
void crear_un_thumb_MAP(struct t_listboxbr * l);
void crear_un_thumb_PAL(struct t_listboxbr * l);
void crear_un_thumb_FNT(struct t_listboxbr * l);
void crear_un_thumb_IFS(struct t_listboxbr * l);
void crear_un_thumb_PCM(struct t_listboxbr * l);
void carga_letra(char letra);
void muestra_thumb(struct t_listboxbr * l, int num);
void browser0(void);
void browser1(void);
void browser2(void);
void browser3(void);
void dir_abrirbr(void);
void pinta_listboxbr(struct t_listboxbr * l);
void pinta_sliderbr(struct t_listboxbr * l);
void crear_listboxbr(struct t_listboxbr * l);
void actualiza_listboxbr(struct t_listboxbr * l);

/* ---- divfont.cpp ---- */
void ShowText(void);
void Fonts1(void);
void close_old_fnt(void);
void Fonts2(void);
void Fonts3(void);
void Fonts0(void);
void OpenGenFont(void);
int CreateFont(int GenCode);
void GetFont(void);
void GetIfs(void);
void Selcolor1(void);
void Selcolor2(void);
void Selcolor3(void);
void Selcolor0(void);
void Preview1(void);
void Preview2(void);
void Preview0(void);
void Preview(void);
void Preview_2(void);
void GenFont1(void);
void GenFont2(void);
void GenFont3(void);
void GenFont0(void);
void Preview21(void);
void Preview22(void);
void Preview20(void);
void crear_texto_prueba(char * s, char flags);
void ShowFont1(void);
void ShowFont2(void);
void ShowFont3(void);
void ShowFont0(void);
void ReloadFont(int vn, struct tventana *vntn);
void OpenFont(void);
void GetText1(void);
void GetText2(void);
void GetText0(void);
void CreateText(void);
int Save_Font_session(FILE *file,int n);
void Load_Font_session(FILE *file);

/* ---- divfpg.cpp ---- */
void FPG1(void);
void cargar_thumbs(void);
void FPG2(void);
void FPG3(void);
void FPG0N(void);
void FPG0A(void);
int nuevo_fichero(void);
void abrir_fichero(void);
void _ffwrite(byte *Buffer,unsigned int Len,FILE *file);
void Warning1(void);
void Warning2(void);
void Warning0(void);
int RemapAllFiles(int vent);
void GetCode1(void);
void GetCode2(void);
void GetCode3(void);
void GetCode0(void);
void InitGetCode(void);
void Show_Taggeds(void);
void Delete_Taggeds(void);
void printlist1(void);
void printlist2(void);
void printlist0(void);
void Print_List(void);
void FPG_crear_thumbs(void);
void FPG_muestra_thumb(struct t_listboxbr * l, int num);
void FPG_pinta_listboxbr(struct t_listboxbr * l);
void FPG_pinta_sliderbr(struct t_listboxbr * l);
void FPG_crear_listboxbr(struct t_listboxbr * l);
void FPG_actualiza_listboxbr(struct t_listboxbr * l);
void crear_un_thumb_FPG(struct t_listboxbr * l);
void MAPtoFPG(struct tmapa * mapa);
void GetGrafMAP(struct tmapa *mapa, byte *imagen, int x, int y, int ancho, int alto, int cod);
void FPGtoMAP(FPG *MiFPG);
void PutGrafMAP(byte *imagen, byte *mapa, int num);
void emplazar_map(void);
int colisiona_con_map(int n, int x, int y, int an, int al);
void cierra_fpg(char *fpg_path);
int selecciona_fichero(void);
void sustituir_FPG_1(void);
void sustituir_FPG_2(void);
void sustituir_FPG_0(void);

/* ---- fpgfile.cpp ---- */
void ReadHeadImageAndPoints(HeadFPG *MiHeadFPG,FILE *fpg);
void Crear_FPG(FPG *Fpg,char *Name);
int Abrir_FPG(FPG *Fpg,char *Name);
void Sort(FPG *Fpg);
int ReadHead(HeadFPG *MiHeadFPG,FILE *fpg);
void WriteHead(HeadFPG *MiHeadFPG,short *puntos,char *imagen,FILE *fpg);
int Anadir_FPG(FPG *Fpg,int COD,char *tDescrip,char *tFilename,int Ancho,int Alto,int nPuntos,char *Puntos,char *Imagen,int BorrarAntiguo, int get_info);
int RemapAllFileToPal(FPG *Fpg);
void SaveFPG(int n);
int Borrar_FPG(FPG *Fpg,int COD);
int Borrar_muchos_FPG(FPG *Fpg,int taggeds,int *array_del);

/* ---- divforma.cpp ---- */
int es_MAP(byte * buffer);
void descomprime_MAP(byte * buffer, byte * mapa, int vent);
int graba_MAP(byte * mapa, FILE * f);
int es_PCX(byte *buffer);
void descomprime_PCX(byte *buffer, byte *mapa, int vent);
int graba_PCX(byte *mapa,FILE *f);
byte * descomprime_rle(byte * buffer,unsigned int bytes_line,unsigned int last_byte,byte * pDest);
int es_BMP(byte *buffer);
void descomprime_BMP(byte *buffer, byte *mapa, int vent);
int graba_BMP(byte *mapa,FILE *f);
int es_JPG(byte *buffer, int img_filesize);
int descomprime_JPG(byte *buffer, byte *mapa, int vent, int img_filesize);
void quitar_colores(byte * buffer,int len);
int cargadac_FNT(char *name);
int cargadac_FPG(char *name);
int cargadac_PAL(char *name);
int cargadac_MAP(char *name);
int cargadac_PCX(char *name);
int cargadac_BMP(char *name);
int cargadac_JPG(char *name);

/* ---- divsetup.cpp ---- */
void Vid_Setup1(void);
void Vid_Setup2(void);
void Vid_Setup3(void);
void Vid_Setup0(void);
void Get_Tapiz(void);
void Tap_Setup1(void);
void Tap_Setup2(void);
void Tap_Setup3(void);
void Tap_Setup0(void);
int Mem_GetHeapFree(void);
void MemInfo1(void);
void MemInfo2(void);
void MemInfo0(void);
void Cfg_colors(void);
void Cfg_Setup1(void);
void cfg_show_cursor(void);
void cfg_show_font(void);
void cfg_show_mouse(void);
void Cfg_Setup2(void);
void Cfg_Setup3(void);
void Cfg_Setup0(void);
void Cfg_Setup_end(void);
void resize_program(void);
void tapiz_thumb(void);
void preparar_tapiz_temp(void);

#endif
