/* Auto-generated forward declarations for DIV IDE port (E1) */
#ifndef PORT_IDE_FORWARD_DECLS_H
#define PORT_IDE_FORWARD_DECLS_H
#ifdef __cplusplus
extern "C" {
#endif

int Can_UpLoad_Desktop(void);
int GetHeapFree(int RetUsed);
int button_status(int n);
int cadena_encontrada(char *p, char*q, int may_min, int completa);
int calcular_colision(int x,int y,int an,int al);
int colisiona_con(int a, int x, int y, int an, int al);
int comprobar_fichero(void);
int cuanto_colisiona_con(int a, int x, int y, int an, int al);
int determina_calc(void);
int determina_fnt(void);
int determina_fpg(void);
int determina_map(void);
int determina_mapa(void);
int determina_mapa3d(void);
int determina_mod(void);
int determina_pcm(void);
int determina_prg(void);
int determina_prg2(void);
int determina_prj(void);
int flag_status(int n);
int get_slide_x(void);
int get_slide_y(void);
int get_status(int n);
int in_block(void);
int linelen(unsigned char * p);
int nuevo_mapa_carga(int nx,int ny,char *nombre,unsigned char *mapilla);
int rnd(void);
int rnd2(int min,int max);
int text_len2(unsigned char * ptr);
unsigned char rndb(void);
unsigned char* avanza(unsigned char * q);
unsigned char* retrocede(unsigned char * q);
void AplieX(struct tmapa *MiMap,int man,int mal);
void Bin1(void);
void Bin2(void);
void DebugFile(char *Cadena,char *Nombre);
void DebugInfo(char *Msg);
void GetFree4kBlocks(void);
void Print_Program(void);
void Progress0(void);
void Progress1(void);
void Progress2(void);
void Tamnio0(void);
void Tamnio1(void);
void Tamnio2(void);
void Tamnio3(void);
void TratarPaleta0(void);
void TratarPaleta1(void);
void TratarPaleta2(void);
void TratarPaleta3(void);
void _completo(void);
void _fwrite(char * s, unsigned char * buf, int n);
void _parcial(void);
void about0(void);
void about1(void);
void about2(void);
void abrir_mapa(void);
void abrir_mapa3d(void);
void abrir_programa_para_fernando(char *nombre,char *path);
void aceptar1(void);
void aceptar2(void);
void actualiza_caja2(int vent, int x, int y, int an, int al);
void actualiza_dialogos(int x, int y, int an, int al);
void actualiza_menu(int menu,int min,int max);
void actualiza_titulo(void);
void an_comentario(void);
void an_numero(void);
void an_texto(void);
void analiza_textos(void);
void analizar_input(void);
void barra_info(void);
void barras_desplazamiento(void);
void betatest0(void);
void betatest1(void);
void betatest2(void);
void betatest4(void);
void betatest5(void);
void betatest6(void);
void buscar_texto1(void);
void buscar_texto2(void);
void bwput_in_box(unsigned char*copia,int an_real_copia,int an_copia,int al_copia,int x,int y,int n);
void calcula_primer_plano(void);
void carga_Fonts0(void);
void carga_help(int n,int helpal,int helpline,int x1,int x2);
void carga_programa0(void);
void check_free(void);
void check_mouse(void);
void check_oldpif(void);
void chk_demo(void);
void clexico(void);
void coder(unsigned char * ptr, int len, char * clave);
void col_analiza_ltlex(void);
void col_analiza_ltobj(void);
void col_error(int n, int m);
void comprobar_memoria(int bloque_lon);
void copy(int a,int b);
void copy_block(unsigned char *d,unsigned char *s,int an,int al);
void copyright1(void);
void copyright2(void);
void crea_barratitulo(void);
void crea_gama(struct _gcolor * t_gama, unsigned char * gama);
void crear_lista_procesos(char * buffer, int file_lon);
void crear_listbox(struct t_listbox * l);
void crear_menu(int menu);
void default_reglas(void);
void delete_line(void);
void delete_text_cursor(void);
void demo0(void);
void demo1(void);
void demo2(void);
void demo3(void);
void desactivar(void);
void determina_unidades(void);
void dir_abrir(void);
void draw_selection_box(int _x0,int _y0,int _x1,int _y1);
void draw_selection_mab(void);
void dummy_handler(void);
void editor(void);
void entorno(void);
void entorno_dialogo(void);
void err1(void);
void err2(void);
void errhlp0(void);
void errhlp1(void);
void errhlp2(void);
void error_cursor(void);
void error_cursor2(void);
void extrude(int x,int y,int an,int al,int x2,int y2,int an2,int al2);
void f_avpag(void);
void f_backspace(void);
void f_bof(void);
void f_cortar(int borrar);
void f_cortar_bloque(int borrar);
void f_delete(void);
void f_desmarcar(void);
void f_destabulador(void);
void f_down(void);
void f_enter(void);
void f_eof(void);
void f_eop(void);
void f_fin(void);
void f_insert(void);
void f_insertar(void);
void f_left(void);
void f_marcar(void);
void f_pegar_bloque(void);
void f_repag(void);
void f_right(void);
void f_sobreescribir(void);
void f_suprimir(void);
void f_tabulador(void);
void f_up(void);
void f_word_left(void);
void f_word_right(void);
void f_word_right2(void);
void fill_draw(void);
void fill_inter(int an,int al);
void fill_scan(unsigned short x,unsigned short y);
void finalizacion(void);
void gama0(void);
void gama1(void);
void gama2(void);
void gama3(void);
void gen_char(unsigned char * di,int an,int al,int inc,char * si);
void gen_fontmap(void);
void get_input(int n);
void goto_error(void);
void guardar_mapa(void);
void imp_fontmap(void);
void implode(int x,int y,int an,int al);
void imprime_ruta(void);
void info0(void);
void inicializa_entorno(void);
void inicializa_textos(unsigned char * fichero);
void inicializacion(void);
void init_lexcolor(void);
void init_rnd(int n, char * clave);
void interr0(void);
void interr1(void);
void interr2(void);
void intmsg0(void);
void intmsg1(void);
void intmsg2(void);
void lista_procesos0(void);
void lista_procesos1(void);
void lista_procesos2(void);
void mapa1(void);
void mapa2(void);
void mapa3(void);
void mapa_busqueda(void);
void mapbus0(void);
void mapbus1(void);
void mapbus2(void);
void mapbus3(void);
void maximizar(void);
void menu_edicion1(void);
void menu_edicion2(void);
void menu_fuentes1(void);
void menu_fuentes2(void);
void menu_graficos1(void);
void menu_graficos2(void);
void menu_mapas1(void);
void menu_mapas2(void);
void menu_mapas3D1(void);
void menu_mapas3D2(void);
void menu_paletas1(void);
void menu_paletas2(void);
void menu_principal0(void);
void menu_principal1(void);
void menu_principal2(void);
void menu_principal3(void);
void menu_programas1(void);
void menu_programas2(void);
void menu_sistema1(void);
void menu_sistema2(void);
void menu_sonidos1(void);
void menu_sonidos2(void);
void minimiza_ventana(void);
void muestra_papelera(void);
void mueve_ventana(void);
void mueve_ventana_completa(void);
void nuevo_mapa0(void);
void nuevo_mapa1(void);
void nuevo_mapa2(void);
void nuevo_mapa3d_carga(void);
void paleta1(void);
void pinta_menu(int menu);
void pinta_segmento_procesos(void);
void pinta_slider(struct t_listbox * l);
void pintar_lista_procesos(void);
void posicion_menos_mala(int*_x,int*_y,int an,int al);
void printprogram0(void);
void printprogram1(void);
void printprogram2(void);
void process_button(int n,int e);
void process_flag(int n,int e);
void process_get(int n,int e);
void programa0(void);
void programa1(void);
void programa2(void);
void programa3(void);
void put_char(unsigned char * ptr, int an, unsigned char c,int block);
void put_char2(unsigned char * ptr, int an, unsigned char c,unsigned char color);
void put_char3(unsigned char * ptr, int an, unsigned char c,int block, unsigned char color);
void quitar_espacios(void);
void read_mouse3(void);
void rellena_colin(void);
void resize(void);
void restaura_tapiz(int x,int y,int an,int al);
void save_prg_buffer(int n);
void select_button(struct t_item * i,int activo);
void select_get(struct t_item * i,int activo,int ocultar_error);
void shell(void);
void show_button(struct t_item * i);
void show_flag(struct t_item * i);
void show_get(struct t_item * i);
void sustituciones0(void);
void sustituciones1(void);
void sustituciones2(void);
void sustituir0(void);
void sustituir1(void);
void sustituir2(void);
void sustituir_texto(void);
void sustituir_texto1(void);
void sustituir_texto2(void);
void test0(void);
void test1(void);
void test2(void);
void test_cursor(void);
void test_cursor2(void);
void text_cursor(void);
void usuario0(void);
void usuario1(void);
void usuario2(void);
void usuario3(void);
void volcado_inter(int an);
void wgra(unsigned char*copia,int an_copia,int al_copia,unsigned char color,int x,int y,int an,int al);
void writetxt(int x,int y,int centro,unsigned char * ptr);
void wtexc(unsigned char*copia,int an_real_copia,int an_copia,int al_copia, unsigned char*p,int x,int y,unsigned char an,int al,unsigned char c);
void wtexn(unsigned char*copia,int an_real_copia,unsigned char*p,int x,int y,unsigned char an,int al,unsigned char c);
void xchg_block(unsigned char *d,unsigned char *s,int an,int al);

/* PORT (E4): definida en port_ide_compila.c. Sustituye al
 * `modo_de_retorno=1; salir_del_entorno=1;` de las rutas de "Probar"
 * (parches byte-exactos en div.cpp / divhandl.cpp): lanza div32run_port
 * sobre el .div32 recien compilado y espera, sin cerrar el IDE. */
void port_ide_tras_compilar_ok(void);

/* PORT (E8, divhelp.cpp): mismo patron K&R de siempre -- llamadas antes de
 * la definicion, dentro del propio fichero. */
void resize_help(void);
void help_xref(int n,int linea);
void arregla_linea(unsigned char * end,int chars,int help_an);
void vuelca_help(void);
void put_image_line(int n,int linea,unsigned char * di,int v_an);
void put_chr(unsigned char * ptr, int an, unsigned char c, unsigned char color);
void Print_Help(void);

/* PORT (E9, divcalc.cpp): mismo patron K&R de siempre. */
void expres0(void);
void expres1(void);
void expres2(void);
void expres3(void);
void expres4(void);
void expres5(void);
void get_token(void);

#ifdef __cplusplus
}
#endif
#endif
